apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-disk
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS
  location: EAST US  # Replace with your Azure region
  kind: Managed
  storageaccounttype: Standard_LRS