apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
  namespace: ingress-nginx
spec:
  accessModes:
    - ReadWriteOnce  # Access mode must match the PV's access mode
  resources:
    requests:
      storage: 1Gi  # Storage size requested, must not exceed the capacity of the PV
  storageClassName: local-storage